<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="E:\Application\Features\Technicians###\AddProfession\AddTechnicianProfessionCommand.cs" Link="features\Technician\Commands\AddProfession\AddTechnicianProfessionCommand.cs" />
    <Compile Include="E:\Application\Features\Technicians###\AddProfession\AddTechnicianProfessionCommandHandler.cs" Link="features\Technician\Commands\AddProfession\AddTechnicianProfessionCommandHandler.cs" />
    <Compile Include="E:\Application\Features\Technicians###\AddProfession\AddTechnicianProfessionCommandValidator.cs" Link="features\Technician\Commands\AddProfession\AddTechnicianProfessionCommandValidator.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeServices.Domain\HomeServices.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behavior\" />
    <Folder Include="Common\Dtos\" />
    <Folder Include="features\Offer\" />
    <Folder Include="features\Technician\Commands\AddProfession\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
  </ItemGroup>

</Project>
